export const worksData = [
    {
        id: 1,
        title: "Vivanta Apartment",
        completion_Data: "2023",
        project_location: "Jaipur, Rajasthan",
        project_type: "New Build",
        project_desc: [
            "A modern, straight-lined apartment crafted for a family of three.",
            "Designed to balance functionality with calm, restorative spaces.",
            "Sleek finishes and concealed storage create a light, clutter-free home.",
            "Executed through detailed planning and streamlined project management.",
        ],
        HeroImg: "/Images/projects/vivanta/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/vivanta/img_4.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_6.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_1.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_11.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_7.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_2.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_13.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_3.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_5.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_8.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_10.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_12.webp" },
        ],
        tags: [
            "Modern Minimalism",
            "Functional Design",
            "Concealed Storage",
            "Warm Interiors",
            "Project Management",
            "Timeless Aesthetic"
        ],
    },
    {
        id: 2,
        title: "RIDANKO Office",
        completion_Data: "2023",
        project_location: "Jaipur, Rajasthan",
        project_type: "New Build",
        project_desc: [
            "A compact marketing office designed for flexibility and efficiency.",
            "Central zone transforms from meeting space to creative studio setup.",
            "Muted modern palette provides a professional yet adaptable backdrop.",
            "Smart storage and precise planning ensured clutter-free functionality.",
        ],
        HeroImg: "/Images/projects/ridanko/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/ridanko/img_4.webp" },
            { type: "portrait", img: "/Images/projects/ridanko/img_6.webp" },
            { type: "landscape", img: "/Images/projects/ridanko/img_1.webp" },
            { type: "portrait", img: "/Images/projects/ridanko/img_2.webp" },
            { type: "portrait", img: "/Images/projects/ridanko/img_3.webp" },
            { type: "landscape", img: "/Images/projects/ridanko/img_5.webp" },
        ],
        tags: [
            "Flexible Workspace",
            "Compact Design",
            "Adaptive Interiors",
            "Modern Palette",
            "Creative Studio",
            "Smart Storage"
        ],
    },
    {
        id: 3,
        title: "2 Bedroom Renovation",
        completion_Data: "2023",
        project_location: "Jaipur, Rajasthan",
        project_type: "New Build",
        project_desc: [
            "Two sleek bedrooms designed to feel restful, modern, and clutter-free.",
            "Feature wall panelling adds depth while maintaining an airy ambiance.",
            "Integrated wardrobes maximize storage without visual heaviness.",
            "Efficient coordination ensured every detail met the client’s vision.",
        ],
        HeroImg: "/Images/projects/2bedroom/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/2bedroom/img_4.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_6.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_1.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_2.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_3.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_5.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_7.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_8.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_9.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_10.webp" },
        ],
        tags: [
            "Bedroom Design",
            "Sleek Interiors",
            "Modern Detailing",
            "Integrated Storage",
            "Minimal Aesthetic",
            "Functional Elegance"
        ],
    },
    {
        id: 4,
        title: "2BHK Airbnb",
        completion_Data: "2024",
        project_location: "Jaipur, Rajasthan",
        project_type: "Renovation",
        project_desc: [
            "A heritage-inspired Airbnb blending Jaipur’s culture with modern living.",
            "Traditional motifs reinterpreted in a sleek, contemporary style.",
            "Durable materials ensure longevity for frequent guest use.",
            "Executed with detailed supervision and on-time project delivery.",
        ],
        HeroImg: "/Images/projects/airbnb/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/airbnb/img_4.webp" },
            { type: "portrait", img: "/Images/projects/airbnb/img_6.webp" },
            { type: "landscape", img: "/Images/projects/airbnb/img_1.webp" },
            { type: "portrait", img: "/Images/projects/airbnb/img_2.webp" },
            { type: "portrait", img: "/Images/projects/airbnb/img_3.webp" },
            { type: "landscape", img: "/Images/projects/airbnb/img_5.webp" },
            { type: "portrait", img: "/Images/projects/airbnb/img_7.webp" },
            { type: "portrait", img: "/Images/projects/airbnb/img_8.webp" },
        ],
        tags: [
            "Heritage Modern",
            "Airbnb Design",
            "Durable Finishes",
            "Cultural Aesthetic",
            "Guest Experience",
            "Timely Execution"
        ],
    },
    {
        id: 5,
        title: "3BHK Apartment",
        completion_Data: "2024",
        project_location: "Jaipur, Rajasthan",
        project_type: "Renovation",
        project_desc: [
            "A contemporary home layered with heritage-inspired details.",
            "Gallery wall showcases family legacy through curated art pieces.",
            "Muted palette and balanced layouts maintain openness and calm.",
            "Seamless vendor coordination ensured flawless project execution.",
        ],
        HeroImg: "/Images/projects/apartment/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/apartment/img_1.webp" },
            { type: "portrait", img: "/Images/projects/apartment/img_2.webp" },
            { type: "landscape", img: "/Images/projects/apartment/img_3.webp" },
        ],
        tags: [
            "Modern Heritage",
            "Gallery Wall",
            "Curated Interiors",
            "Balanced Layouts",
            "Cultural Identity",
            "Refined Aesthetic"
        ],
    },
    {
        id: 6,
        title: "Gemstone Application Renders",
        completion_Data: "2022",
        project_location: "Jaipur, Rajasthan",
        project_type: "3D Visualisation",
        project_desc: [
            "Conceptual renders showcasing gemstone panels in diverse interiors.",
            "Focused on balancing luxury materials with functional design.",
            "Checklists ensured stones remained the hero of each render.",
            "Streamlined feedback led to efficient, high-quality visual delivery.",
        ],
        HeroImg: "/Images/projects/gemstone/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/gemstone/img_4.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_6.webp" },
            { type: "landscape", img: "/Images/projects/gemstone/img_1.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_7.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_2.webp" },
            { type: "landscape", img: "/Images/projects/gemstone/img_3.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_5.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_8.webp" },
        ],
        tags: [
            "3D Renders",
            "Luxury Materials",
            "Gemstone Design",
            "Visual Storytelling",
            "Functional Aesthetics",
            "Client Collaboration"
        ],
    },
    {
        id: 7,
        title: "Illustrations",
        completion_Data: "2022–2025",
        project_location: "Jaipur",
        project_type: "Illustrations",
        project_desc: [
            "Hand-drawn visuals bringing warmth and individuality to design.",
            "Detailed sketches translate complex spaces into accessible drawings.",
            "Layered checklists ensured accuracy across all illustrations.",
            "Became a signature element of Arujak’s bespoke design process.",
        ],
        HeroImg: "/Images/projects/illustrations/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/illustrations/img_4.webp" },
            { type: "portrait", img: "/Images/projects/illustrations/img_6.webp" },
            { type: "landscape", img: "/Images/projects/illustrations/img_1.webp" },
            { type: "portrait", img: "/Images/projects/illustrations/img_7.webp" },
            { type: "portrait", img: "/Images/projects/illustrations/img_3.webp" },
            { type: "landscape", img: "/Images/projects/illustrations/img_2.webp" },
            { type: "portrait", img: "/Images/projects/illustrations/img_5.webp" },
            { type: "portrait", img: "/Images/projects/illustrations/img_8.webp" },
        ],
        tags: [
            "Hand-Drawn Art",
            "Design Communication",
            "Detailed Sketches",
            "Warm Aesthetic",
            "Creative Process",
            "Artistic Visualization"
        ],
    },
    {
        id: 8,
        title: "Moodboards",
        completion_Data: "2022–2025",
        project_location: "Jaipur, Rajasthan",
        project_type: "Space Stories",
        project_desc: [
            "Comprehensive boards capturing the full essence of each space.",
            "Bridge the gap between design intent and spatial visualization.",
            "Encourage client feedback early to refine design direction.",
            "Streamlined through checklists and tracked revisions for accuracy.",
        ],
        HeroImg: "/Images/projects/moodboards/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/moodboards/img_10.webp" },
            { type: "portrait", img: "/Images/projects/moodboards/img_6.webp" },
            { type: "landscape", img: "/Images/projects/moodboards/img_4.webp" },
            { type: "landscape", img: "/Images/projects/moodboards/img_1.webp" },
            { type: "portrait", img: "/Images/projects/moodboards/img_7.webp" },
            { type: "portrait", img: "/Images/projects/moodboards/img_8.webp" },
            { type: "landscape", img: "/Images/projects/moodboards/img_2.webp" },
            { type: "portrait", img: "/Images/projects/moodboards/img_5.webp" },
            { type: "portrait", img: "/Images/projects/moodboards/img_9.webp" },
            { type: "landscape", img: "/Images/projects/moodboards/img_3.webp" },
        ],
        tags: [
            "Design Visualization",
            "Concept Boards",
            "Client Collaboration",
            "Visual Clarity",
            "Holistic Design",
            "Efficient Workflow"
        ],
    },
    {
        id: 9,
        title: "Rohit Polymers Office",
        completion_Data: "2023",
        project_location: "Jaipur, Rajasthan",
        project_type: "New Build",
        project_desc: [
            "Compact office designed to maximize function and visual openness.",
            "Smart layouts and integrated storage enhance efficiency.",
            "Neutral palette adds sophistication within limited space.",
            "Planned meticulously through checklists and precise coordination.",
        ],
        HeroImg: "/Images/projects/polymer/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/polymer/img_4.webp" },
            { type: "portrait", img: "/Images/projects/polymer/img_1.webp" },
            { type: "landscape", img: "/Images/projects/polymer/img_2.webp" },
            { type: "portrait", img: "/Images/projects/polymer/img_3.webp" },
            { type: "portrait", img: "/Images/projects/polymer/img_5.webp" },
        ],
        tags: [
            "Compact Office",
            "Smart Planning",
            "Integrated Design",
            "Space Optimization",
            "Modern Workspace",
            "Efficient Execution"
        ],
    },
    {
        id: 10,
        title: "Contemporary Airbnb Rental",
        completion_Data: "2025",
        project_location: "Jaipur, Rajasthan",
        project_type: "New Build",
        project_desc: [
            "A warm, nature-inspired Airbnb blending modern comfort with calm.",
            "Natural materials like wood and cane add organic character.",
            "Layouts optimized for guest comfort and aesthetic balance.",
            "Delivered through clear moodboards and structured coordination.",
        ],
        HeroImg: "/Images/projects/rental/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/rental/img_1.webp" },
            { type: "portrait", img: "/Images/projects/rental/img_2.webp" },
            { type: "landscape", img: "/Images/projects/rental/img_3.webp" },
        ],
        tags: [
            "Natural Interiors",
            "Airbnb Design",
            "Warm Minimalism",
            "Guest Comfort",
            "Organic Materials",
            "Contemporary Living"
        ],
    },
    //   {
    //     id: 11,
    //     title: "Laundry House Feature Wall",
    //     completion_Data: "2024",
    //     project_location: "Jaipur, Rajasthan",
    //     project_type: "Renovation/Styling",
    //     project_desc: [
    //       "A creative reinterpretation of a feature wall using 3D framed objects.",
    //       "Adds personality while maintaining balance within the interiors.",
    //       "Design detailing ensured harmony between objects and finishes.",
    //       "Executed efficiently alongside ongoing home renovation works.",
    //     ],
    // HeroImg: "/Images/projects/vivanta/heroImg.webp",
    // images: [
    //     { type: "landscape", img: "/Images/HomePage/cdcs.webp" },
    //     { type: "landscape", img: "/Images/projects/vivanta/heroImg.webp" },
    //     { type: "portrait", img: "/Images/HomePage/FooterImg.webp" },
    //     { type: "portrait", img: "/Images/HomePage/erec.webp" },
    //     { type: "landscape", img: "/Images/HomePage/wmdsc.webp" },
    //     { type: "landscape", img: "/Images/HomePage/FooterImg.webp" },
    //     { type: "portrait", img: "/Images/HomePage/FooterImg.webp" },
    //     { type: "portrait", img: "/Images/HomePage/erec.webp" },
    //     { type: "landscape", img: "/Images/HomePage/wmdsc.webp" },
    //     { type: "landscape", img: "/Images/HomePage/FooterImg.webp" },
    // ],
    //     tags: [
    //       "Feature Wall",
    //       "3D Installation",
    //       "Creative Styling",
    //       "Balanced Design",
    //       "Detail Coordination",
    //       "Home Integration"
    //     ],
    //   },
];
